name = "ODEInterface"
uuid = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
license = "MIT"
authors = ["Christian Ludwig <ludwig@ma.tum.de>"]
version = "0.5.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ODEInterface_jll = "c771fb93-2439-5ece-a3b3-58fecce82101"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
